server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 10086
  undertow:
    max-http-post-size: -1
    buffer-size: 256
    direct-buffers: true
    threads:
      io: 12
      worker: 256
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # 排除不需要的自动配置
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active: @profiles.active@
  application:
    name: bilibili-balabala-boomb
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    dynamic:
      datasource:
        index_A:
          lazy: true
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://6.6.6.6:6666/index_A?useSSL=false&serverTimezone=UTC
          username: 666
          password: 666
        index_B:
          lazy: true
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://6.6.6.6:6666/index_B?useSSL=false&serverTimezone=UTC
          username: 666
          password: 666
      primary: index_A
  session:
    redis:
      namespace: bilibili:session
      flush-mode: on_save
      save-mode: always
      repository-type: indexed
    timeout: 30m
  data:
    redis:
      host: 6.6.6.6
      port: 6379
      database: 0
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: bilibili.balabala.pupupu.model
mybatis-plus:
  configuration:
    logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    aggressive-lazy-loading: true
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: none
    auto-mapping-behavior: partial
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: bilibili.balabala.**.model
